#!/bin/zsh
echo "$HOME"
source ~/activate_conda.sh
conda activate egb
cd /Users/akarshkumar0101/exploration-generalization/atari2

CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_best_0_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/4.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_leaf_0_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/19.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_None_0_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/34.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_best_1_0000" --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/49.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_leaf_1_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/64.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_None_1_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/79.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_best_2_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/94.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_leaf_2_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/109.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_None_2_0000"      --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/124.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_best_3_0000"      --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/139.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Alien_None_3_0000"            --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Alien            --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/154.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_best_0_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/169.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_leaf_0_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/184.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_None_0_0001"           --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/199.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_best_1_0001"       --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/214.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_leaf_1_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/229.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Krull_None_1_0001"            --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Krull            --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/244.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Hero_best_2_0001"             --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Hero             --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/259.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_leaf_2_0001"            --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/274.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_None_2_0001"         --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/289.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_best_3_0001"    --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/304.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_leaf_3_0001"           --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/319.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Venture_None_3_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Venture          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/334.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Surround_best_0_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Surround         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/349.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Assault_None_0_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Assault          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/364.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_best_1_0002"       --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/379.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_leaf_1_0002"   --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/394.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_None_1_0002"     --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/409.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Defender_best_2_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Defender         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/424.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_leaf_2_0002"      --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/439.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_None_2_0002"     --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/454.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_best_3_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/469.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Pong_leaf_3_0002"             --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/484.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_None_3_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/499.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_best_0_0003"       --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/514.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_leaf_0_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/529.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_None_0_0003"       --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/544.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_best_1_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/559.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_None_1_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/574.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_best_2_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/589.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_leaf_2_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/604.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_None_2_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/619.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_best_3_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/634.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_leaf_3_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/649.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_None_3_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/664.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_best_0_0004"     --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/679.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_leaf_0_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/694.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_None_0_0004"     --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/709.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_best_1_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/724.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_leaf_1_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/739.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_None_1_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/754.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_best_2_0004"           --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/769.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_None_2_0004"           --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/784.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_best_3_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/799.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_leaf_3_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/814.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_None_3_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/829.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_best_0_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/844.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_leaf_0_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/859.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_None_0_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/874.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_best_1_0005" --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/889.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_leaf_1_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/904.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_None_1_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/919.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_best_2_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/934.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_leaf_2_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/949.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_None_2_0005"      --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/964.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_best_3_0005"      --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/979.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Alien_None_3_0005"            --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Alien            --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/994.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_best_0_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1009.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_leaf_0_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1024.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_None_0_0006"           --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1039.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_best_1_0006"       --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1054.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_leaf_1_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1069.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Krull_None_1_0006"            --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Krull            --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1084.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Hero_best_2_0006"             --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Hero             --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1099.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_leaf_2_0006"            --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1114.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_None_2_0006"         --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1129.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_best_3_0006"    --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1144.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_leaf_3_0006"           --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1159.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Venture_None_3_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Venture          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1174.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Surround_best_0_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Surround         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1189.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Assault_None_0_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Assault          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1204.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_best_1_0007"       --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1219.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_leaf_1_0007"   --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1234.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_None_1_0007"     --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1249.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Defender_best_2_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Defender         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1264.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_leaf_2_0007"      --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1279.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_None_2_0007"     --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1294.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_best_3_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1309.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Pong_leaf_3_0007"             --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1324.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_None_3_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1339.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_best_0_0008"       --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1354.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_leaf_0_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1369.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_None_0_0008"       --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1384.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_best_1_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1399.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_None_1_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1414.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_best_2_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1429.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_leaf_2_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1444.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_None_2_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1459.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_best_3_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1474.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_leaf_3_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1489.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_None_3_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1504.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_best_0_0009"     --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1519.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_leaf_0_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1534.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_None_0_0009"     --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1549.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_best_1_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1564.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_leaf_1_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1579.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_None_1_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1594.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_best_2_0009"           --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1609.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_None_2_0009"           --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1624.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_best_3_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1639.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_leaf_3_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1654.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_None_3_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1669.log &
echo "launched 4 jobs"
wait