#!/bin/zsh
echo "$HOME"
source ~/activate_conda.sh
conda activate egb
cd /Users/akarshkumar0101/exploration-generalization/atari2

CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_best_0_0000"     --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/7.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_leaf_0_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/22.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_None_0_0000"     --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/37.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_best_1_0000"       --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/52.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_leaf_1_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/67.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_None_1_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/82.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_best_2_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/97.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_None_2_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/112.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_best_3_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/127.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_leaf_3_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/142.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_None_3_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/157.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_best_0_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/172.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_leaf_0_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/187.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_None_0_0001"         --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/202.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_best_1_0001" --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/217.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_leaf_1_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/232.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_None_1_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/247.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_best_2_0001"         --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/262.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_leaf_2_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/277.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_None_2_0001"      --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/292.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_best_3_0001"      --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/307.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Alien_None_3_0001"            --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Alien            --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/322.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_best_0_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/337.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_leaf_0_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/352.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_None_0_0002"           --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/367.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_best_1_0002"       --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/382.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_leaf_1_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/397.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Krull_None_1_0002"            --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Krull            --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/412.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Hero_best_2_0002"             --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Hero             --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/427.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_leaf_2_0002"            --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/442.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_None_2_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/457.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_best_3_0002"    --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/472.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_leaf_3_0002"           --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/487.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Venture_None_3_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Venture          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/502.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Surround_best_0_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Surround         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/517.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Assault_None_0_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Assault          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/532.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_best_1_0003"       --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/547.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_leaf_1_0003"   --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/562.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_None_1_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/577.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Defender_best_2_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Defender         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/592.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_leaf_2_0003"      --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/607.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_None_2_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/622.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_best_3_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/637.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Pong_leaf_3_0003"             --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/652.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_None_3_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/667.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_best_0_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/682.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_leaf_0_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/697.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_None_0_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/712.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_best_1_0004"     --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/727.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_None_1_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/742.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_best_2_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/757.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_leaf_2_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/772.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_None_2_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/787.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_best_3_0004"           --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/802.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_leaf_3_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/817.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_None_3_0004"           --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/832.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_best_0_0005"     --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/847.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_leaf_0_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/862.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_None_0_0005"     --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/877.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_best_1_0005"       --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/892.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_leaf_1_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/907.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_None_1_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/922.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_best_2_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/937.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_None_2_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/952.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_best_3_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/967.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_leaf_3_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/982.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_None_3_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/997.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_best_0_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1012.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_leaf_0_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1027.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_None_0_0006"         --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1042.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_best_1_0006" --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1057.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_leaf_1_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1072.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_None_1_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1087.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_best_2_0006"         --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1102.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_leaf_2_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1117.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_None_2_0006"      --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1132.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_best_3_0006"      --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1147.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Alien_None_3_0006"            --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Alien            --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1162.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_best_0_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1177.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_leaf_0_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1192.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_None_0_0007"           --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1207.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_best_1_0007"       --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1222.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_leaf_1_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1237.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Krull_None_1_0007"            --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Krull            --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1252.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Hero_best_2_0007"             --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Hero             --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1267.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_leaf_2_0007"            --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1282.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_None_2_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1297.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_best_3_0007"    --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1312.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_leaf_3_0007"           --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1327.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Venture_None_3_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Venture          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1342.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Surround_best_0_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Surround         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1357.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Assault_None_0_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Assault          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1372.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_best_1_0008"       --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1387.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_leaf_1_0008"   --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1402.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_None_1_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1417.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Defender_best_2_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Defender         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1432.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_leaf_2_0008"      --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1447.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_None_2_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1462.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_best_3_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1477.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Pong_leaf_3_0008"             --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1492.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_None_3_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1507.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_best_0_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1522.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_leaf_0_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1537.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_None_0_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1552.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_best_1_0009"     --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1567.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_None_1_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1582.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_best_2_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1597.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_leaf_2_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1612.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_None_2_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1627.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_best_3_0009"           --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1642.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_leaf_3_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1657.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_None_3_0009"           --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1672.log &
echo "launched 4 jobs"
wait