#!/bin/zsh
echo "$HOME"
source ~/activate_conda.sh
conda activate egb
cd /Users/akarshkumar0101/exploration-generalization/atari2

CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_best_0_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/2.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_leaf_0_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/17.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_None_0_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/32.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_best_1_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/47.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Krull_leaf_1_0000"            --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Krull            --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/62.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_None_1_0000" --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/77.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_best_2_0000"            --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/92.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_leaf_2_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/107.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_None_2_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/122.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_best_3_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/137.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Venture_leaf_3_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Venture          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/152.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_None_3_0000"      --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/167.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Assault_leaf_0_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Assault          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/182.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_None_0_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/197.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_best_1_0001"   --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/212.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_leaf_1_0001"     --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/227.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_None_1_0001"       --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/242.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_best_2_0001"      --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/257.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_leaf_2_0001"     --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/272.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Hero_None_2_0001"             --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Hero             --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/287.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Pong_best_3_0001"             --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/302.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_leaf_3_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/317.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_None_3_0001"    --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/332.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_best_0_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/347.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_leaf_0_0002"       --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/362.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Surround_None_0_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Surround         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/377.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_leaf_1_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/392.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_None_1_0002"       --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/407.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_best_2_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/422.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_leaf_2_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/437.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Defender_None_2_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Defender         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/452.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_best_3_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/467.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_leaf_3_0002"           --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/482.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_None_3_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/497.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_best_0_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/512.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_leaf_0_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/527.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_None_0_0003"       --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/542.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_best_1_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/557.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_leaf_1_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/572.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_None_1_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/587.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_leaf_2_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/602.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_None_2_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/617.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_best_3_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/632.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_leaf_3_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/647.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_None_3_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/662.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_best_0_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/677.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_leaf_0_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/692.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_None_0_0004"     --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/707.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_best_1_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/722.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_leaf_1_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/737.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_None_1_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/752.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_best_2_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/767.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_leaf_2_0004"      --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/782.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_None_2_0004"           --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/797.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Alien_leaf_3_0004"            --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Alien            --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/812.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_None_3_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/827.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_best_0_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/842.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_leaf_0_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/857.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_None_0_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/872.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_best_1_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/887.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Krull_leaf_1_0005"            --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Krull            --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/902.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_None_1_0005" --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/917.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_best_2_0005"            --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/932.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_leaf_2_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/947.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_None_2_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/962.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_best_3_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/977.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Venture_leaf_3_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Venture          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/992.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_None_3_0005"      --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1007.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Assault_leaf_0_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Assault          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1022.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_None_0_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1037.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_best_1_0006"   --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1052.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_leaf_1_0006"     --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1067.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_None_1_0006"       --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1082.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_best_2_0006"      --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1097.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_leaf_2_0006"     --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1112.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Hero_None_2_0006"             --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Hero             --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1127.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Pong_best_3_0006"             --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1142.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_leaf_3_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1157.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_None_3_0006"    --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1172.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_best_0_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1187.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_leaf_0_0007"       --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1202.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Surround_None_0_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Surround         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1217.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_leaf_1_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1232.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_None_1_0007"       --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1247.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_best_2_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1262.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_leaf_2_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1277.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Defender_None_2_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Defender         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1292.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_best_3_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1307.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_leaf_3_0007"           --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1322.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_None_3_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1337.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_best_0_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1352.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_leaf_0_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1367.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_None_0_0008"       --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1382.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_best_1_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1397.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_leaf_1_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1412.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_None_1_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1427.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_leaf_2_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1442.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_None_2_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1457.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_best_3_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1472.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_leaf_3_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1487.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_None_3_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1502.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_best_0_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1517.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_leaf_0_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1532.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_None_0_0009"     --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1547.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_best_1_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1562.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_leaf_1_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1577.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_None_1_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1592.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_best_2_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1607.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_leaf_2_0009"      --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1622.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_None_2_0009"           --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1637.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Alien_leaf_3_0009"            --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Alien            --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1652.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_None_3_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1667.log &
echo "launched 4 jobs"
wait