#!/bin/zsh
echo "$HOME"
source ~/activate_conda.sh
conda activate egb
cd /Users/akarshkumar0101/exploration-generalization/atari2

CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_best_0_0000"     --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/9.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_leaf_0_0000"       --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/24.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_None_0_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/39.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_best_1_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/54.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_leaf_1_0000"     --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/69.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_best_2_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/84.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_leaf_2_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/99.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_None_2_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/114.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_best_3_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/129.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_leaf_3_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/144.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_None_3_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/159.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_best_0_0001"         --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/174.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_leaf_0_0001"     --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/189.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_None_0_0001"         --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/204.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_best_1_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/219.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_leaf_1_0001"       --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/234.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_None_1_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/249.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_best_2_0001"      --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/264.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_leaf_2_0001"           --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/279.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Alien_best_3_0001"            --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Alien            --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/294.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_leaf_3_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/309.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_None_3_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/324.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_best_0_0002"           --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/339.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_leaf_0_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/354.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_None_0_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/369.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Krull_best_1_0002"            --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Krull            --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/384.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_leaf_1_0002" --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/399.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_None_1_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/414.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_best_2_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/429.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_leaf_2_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/444.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_None_2_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/459.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Venture_best_3_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Venture          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/474.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_leaf_3_0002"      --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/489.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Assault_best_0_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Assault          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/504.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_leaf_0_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/519.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_None_0_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/534.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_best_1_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/549.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_leaf_1_0003"       --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/564.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_None_1_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/579.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_best_2_0003"     --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/594.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Hero_leaf_2_0003"             --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Hero             --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/609.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_None_2_0003"            --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/624.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_best_3_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/639.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_leaf_3_0003"    --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/654.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_None_3_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/669.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_best_0_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/684.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Surround_leaf_0_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Surround         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/699.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_best_1_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/714.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_leaf_1_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/729.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_None_1_0004"   --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/744.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_best_2_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/759.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Defender_leaf_2_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Defender         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/774.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_None_2_0004"      --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/789.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_best_3_0004"           --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/804.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_leaf_3_0004"         --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/819.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Pong_None_3_0004"             --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Pong             --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/834.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_best_0_0005"     --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/849.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_leaf_0_0005"       --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/864.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_None_0_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/879.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_best_1_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/894.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_leaf_1_0005"     --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/909.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_best_2_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/924.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_leaf_2_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/939.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_None_2_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/954.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_best_3_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/969.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_leaf_3_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/984.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_None_3_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/999.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_best_0_0006"         --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1014.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_leaf_0_0006"     --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1029.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_None_0_0006"         --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1044.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_best_1_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1059.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_leaf_1_0006"       --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1074.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_None_1_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1089.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_best_2_0006"      --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1104.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_leaf_2_0006"           --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1119.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Alien_best_3_0006"            --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Alien            --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1134.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_leaf_3_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1149.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_None_3_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1164.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_best_0_0007"           --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1179.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_leaf_0_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1194.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_None_0_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1209.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Krull_best_1_0007"            --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Krull            --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1224.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_leaf_1_0007" --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1239.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_None_1_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1254.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_best_2_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1269.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_leaf_2_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1284.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_None_2_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1299.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Venture_best_3_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Venture          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1314.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_leaf_3_0007"      --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1329.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Assault_best_0_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Assault          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1344.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_leaf_0_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1359.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_None_0_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1374.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_best_1_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1389.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_leaf_1_0008"       --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1404.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_None_1_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1419.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_best_2_0008"     --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1434.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Hero_leaf_2_0008"             --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Hero             --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1449.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_None_2_0008"            --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1464.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_best_3_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1479.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_leaf_3_0008"    --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1494.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_None_3_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1509.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_best_0_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1524.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Surround_leaf_0_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Surround         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1539.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_best_1_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1554.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_leaf_1_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1569.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_None_1_0009"   --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1584.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_best_2_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1599.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Defender_leaf_2_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Defender         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1614.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_None_2_0009"      --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1629.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_best_3_0009"           --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1644.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_leaf_3_0009"         --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1659.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Pong_None_3_0009"             --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Pong             --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1674.log &
echo "launched 4 jobs"
wait