#!/bin/zsh
echo "$HOME"
source ~/activate_conda.sh
conda activate egb
cd /Users/akarshkumar0101/exploration-generalization/atari2

CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_best_0_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/11.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_leaf_0_0000"       --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/26.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Surround_None_0_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Surround         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/41.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_leaf_1_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/56.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_None_1_0000"       --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/71.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_best_2_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/86.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_leaf_2_0000"        --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/101.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Defender_None_2_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Defender         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/116.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_best_3_0000"          --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/131.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_leaf_3_0000"           --device="cuda" --seed=0 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/146.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_None_3_0000"         --device="cuda" --seed=0 --model="trans_32" --load_ckpt=None                                           --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/161.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_best_0_0001"         --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/176.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_leaf_0_0001"     --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/191.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_None_0_0001"       --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/206.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_best_1_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/221.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_leaf_1_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/236.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_None_1_0001"     --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/251.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_leaf_2_0001"           --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/266.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_None_2_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/281.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_best_3_0001"        --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/296.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_leaf_3_0001"          --device="cuda" --seed=1 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/311.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_None_3_0001"           --device="cuda" --seed=1 --model="trans_32" --load_ckpt=None                                           --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/326.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_best_0_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/341.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_leaf_0_0002"         --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/356.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_None_0_0002"     --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/371.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_best_1_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/386.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_leaf_1_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/401.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_None_1_0002"       --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/416.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_best_2_0002"        --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/431.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_leaf_2_0002"      --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/446.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_None_2_0002"           --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/461.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Alien_leaf_3_0002"            --device="cuda" --seed=2 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Alien            --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/476.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_None_3_0002"          --device="cuda" --seed=2 --model="trans_32" --load_ckpt=None                                           --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/491.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_best_0_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/506.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_leaf_0_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/521.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_None_0_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/536.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_best_1_0003"        --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/551.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Krull_leaf_1_0003"            --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Krull            --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/566.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_None_1_0003" --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/581.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_best_2_0003"            --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/596.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_leaf_2_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/611.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_None_2_0003"         --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/626.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_best_3_0003"           --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/641.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Venture_leaf_3_0003"          --device="cuda" --seed=3 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Venture          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/656.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_None_3_0003"      --device="cuda" --seed=3 --model="trans_32" --load_ckpt=None                                           --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/671.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Assault_leaf_0_0004"          --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Assault          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/686.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_None_0_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/701.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_best_1_0004"   --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/716.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_leaf_1_0004"     --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/731.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_None_1_0004"       --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/746.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_best_2_0004"      --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/761.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_leaf_2_0004"     --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/776.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Hero_None_2_0004"             --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids Hero             --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/791.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Pong_best_3_0004"             --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/806.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_leaf_3_0004"        --device="cuda" --seed=4 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/821.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_None_3_0004"    --device="cuda" --seed=4 --model="trans_32" --load_ckpt=None                                           --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/836.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Solaris_best_0_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Solaris          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/851.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="StarGunner_leaf_0_0005"       --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids StarGunner       --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/866.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Surround_None_0_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Surround         --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/881.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Atlantis_leaf_1_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Atlantis         --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/896.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="BattleZone_None_1_0005"       --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids BattleZone       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/911.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Breakout_best_2_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Breakout         --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/926.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Centipede_leaf_2_0005"        --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Centipede        --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/941.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Defender_None_2_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Defender         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/956.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Freeway_best_3_0005"          --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Freeway          --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/971.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Gopher_leaf_3_0005"           --device="cuda" --seed=5 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Gopher           --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/986.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Gravitar_None_3_0005"         --device="cuda" --seed=5 --model="trans_32" --load_ckpt=None                                           --env_ids Gravitar         --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1001.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="MsPacman_best_0_0006"         --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids MsPacman         --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1016.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="NameThisGame_leaf_0_0006"     --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids NameThisGame     --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1031.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="RoadRunner_None_0_0006"       --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids RoadRunner       --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1046.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Tutankham_best_1_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Tutankham        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1061.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="UpNDown_leaf_1_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids UpNDown          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1076.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="VideoPinball_None_1_0006"     --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids VideoPinball     --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1091.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Amidar_leaf_2_0006"           --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Amidar           --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1106.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="BeamRider_None_2_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids BeamRider        --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1121.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="BankHeist_best_3_0006"        --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids BankHeist        --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1136.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Berzerk_leaf_3_0006"          --device="cuda" --seed=6 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Berzerk          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1151.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Enduro_None_3_0006"           --device="cuda" --seed=6 --model="trans_32" --load_ckpt=None                                           --env_ids Enduro           --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1166.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="IceHockey_best_0_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids IceHockey        --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1181.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Kangaroo_leaf_0_0007"         --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Kangaroo         --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1196.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="KungFuMaster_None_0_0007"     --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids KungFuMaster     --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1211.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Phoenix_best_1_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Phoenix          --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1226.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Pitfall_leaf_1_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Pitfall          --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1241.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="PrivateEye_None_1_0007"       --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids PrivateEye       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1256.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="TimePilot_best_2_0007"        --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids TimePilot        --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1271.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="YarsRevenge_leaf_2_0007"      --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids YarsRevenge      --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1286.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Zaxxon_None_2_0007"           --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Zaxxon           --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1301.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Alien_leaf_3_0007"            --device="cuda" --seed=7 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Alien            --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1316.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Asterix_None_3_0007"          --device="cuda" --seed=7 --model="trans_32" --load_ckpt=None                                           --env_ids Asterix          --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1331.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Bowling_best_0_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_0_0000/ckpt.pt" --env_ids Bowling          --n_iters=4000 --i_split=0 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1346.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Boxing_leaf_0_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Boxing           --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1361.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Frostbite_None_0_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Frostbite        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1376.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Jamesbond_best_1_0008"        --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids Jamesbond        --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1391.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Krull_leaf_1_0008"            --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids Krull            --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1406.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="MontezumaRevenge_None_1_0008" --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids MontezumaRevenge --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1421.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Qbert_best_2_0008"            --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids Qbert            --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1436.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Robotank_leaf_2_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids Robotank         --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1451.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Seaquest_None_2_0008"         --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids Seaquest         --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1466.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Tennis_best_3_0008"           --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Tennis           --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1481.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="Venture_leaf_3_0008"          --device="cuda" --seed=8 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Venture          --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1496.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="WizardOfWor_None_3_0008"      --device="cuda" --seed=8 --model="trans_32" --load_ckpt=None                                           --env_ids WizardOfWor      --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1511.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Assault_leaf_0_0009"          --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_0_0000/ckpt.pt" --env_ids Assault          --n_iters=4000 --i_split=0 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1526.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Asteroids_None_0_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Asteroids        --n_iters=4000 --i_split=0 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1541.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="ChopperCommand_best_1_0009"   --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_1_0000/ckpt.pt" --env_ids ChopperCommand   --n_iters=4000 --i_split=1 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1556.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="CrazyClimber_leaf_1_0009"     --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_1_0000/ckpt.pt" --env_ids CrazyClimber     --n_iters=4000 --i_split=1 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1571.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="DoubleDunk_None_1_0009"       --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids DoubleDunk       --n_iters=4000 --i_split=1 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1586.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="DemonAttack_best_2_0009"      --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_2_0000/ckpt.pt" --env_ids DemonAttack      --n_iters=4000 --i_split=2 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1601.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="FishingDerby_leaf_2_0009"     --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_2_0000/ckpt.pt" --env_ids FishingDerby     --n_iters=4000 --i_split=2 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1616.log &
echo "launched 4 jobs"
wait
CUDA_VISIBLE_DEVICES=0 python ppo.py --track=True --project="egb_ftppo" --name="Hero_None_2_0009"             --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids Hero             --n_iters=4000 --i_split=2 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1631.log &
CUDA_VISIBLE_DEVICES=1 python ppo.py --track=True --project="egb_ftppo" --name="Pong_best_3_0009"             --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/best_3_0000/ckpt.pt" --env_ids Pong             --n_iters=4000 --i_split=3 --strategy="best" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1646.log &
CUDA_VISIBLE_DEVICES=2 python ppo.py --track=True --project="egb_ftppo" --name="Riverraid_leaf_3_0009"        --device="cuda" --seed=9 --model="trans_32" --load_ckpt="./data/egb_ge_generalist/leaf_3_0000/ckpt.pt" --env_ids Riverraid        --n_iters=4000 --i_split=3 --strategy="leaf" &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1661.log &
CUDA_VISIBLE_DEVICES=3 python ppo.py --track=True --project="egb_ftppo" --name="SpaceInvaders_None_3_0009"    --device="cuda" --seed=9 --model="trans_32" --load_ckpt=None                                           --env_ids SpaceInvaders    --n_iters=4000 --i_split=3 --strategy=None   &> /Users/akarshkumar0101/cluster-run/temp_dir/job_logs/1676.log &
echo "launched 4 jobs"
wait